version: '3.8'

services:
  web:
    restart: unless-stopped
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./db:/app/db
    environment:
      - DATABASE_URL=sqlite:////app/db/test.db
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
