name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Docker
        uses: docker/setup-buildx-action@v2


      - name: Install Docker Compose
        run: |
          # Download docker-compose binary
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          # Make it executable
          sudo chmod +x /usr/local/bin/docker-compose
          # Verify installation
          docker-compose --version


      - name: Fix Docker permissions
        run: |
          sudo groupadd docker || true
          sudo usermod -aG docker $USER
          newgrp docker


      - name: Start containers
        run: docker-compose up -d

      - name: Run pytest
        run: docker-compose exec web pytest
